### ISSUE TITLE
[Smart Contract / Luckbox] Deploy Staging Contracts

### ISSUE THREAD

**Issue by pisuthd** [tamago-finance/tamago-finance#143]
Deploy Luckbox contracts on Kovan through Remix or Hardhat, later we can switch the UI to connect from there.

**Comment by Moopz-Dev** [comment]
Deployed LuckboxUpgradeable in Kovan through Remix :

0x690c5345848Fb55a5B448992a6f327D852C6bf23

NOTE: Initially the contract could not be deployed due to file size causing an error during deployment, the error was prevented by enabling optimization (with default value of 200) during compiler configuration.
